uPortal-Project/uPortal-start

overlays/cas/build.gradle
Resolves issue where `gradle clean build` would fail, due to test compile errors.
=> UP-4781: Add test support to CAS overlay

COMMITTERS.md
Documents in this repo who the Committers are, by referencing the Committers listing for the `Jasig/uPortal` repo.
=> More explicitly document who are Committers for this repo

build.gradle, build.properties.sample, buildSrc/src/main/groovy/org/apereo/portal/start/gradle/plugins/GradleTomcatDeployPlugin.groovy, buildSrc/src/main/resources/buildDefaults.properties, gradle/tasks/tomcat.gradle
https://issues.jasig.org/browse/UP-4888
This is a reboot of https://github.com/Jasig/uPortal-start/pull/24 by @markamace1;  it includes his 2 commits.
=> UP-4888:  Support differentiation between server.home and server.base

.travis.yml
Increase RAM allocation to prevent `Java returned: 137` errors on Linux CI.
=> NOJIRA: Use sudo required to increase RAM allocation to Linux CI

CODE_OF_CONDUCT.md
Acknowledges that as a sponsored Apereo project, uPortal is in-scope for Apereo Welcoming Policy, as `CODE_OF_CONDUCT.md`.
Ref: https://github.com/Jasig/uPortal/pull/931
=> docs: add code of conduct, referencing Apereo welcoming policy

buildSrc/src/main/groovy/org/apereo/portal/start/gradle/plugins/GradleTomcatDeployPlugin.groovy
ensures that `tomcatClean` and `tomcatDeploy` happen after tomcat has been installed.
resolves #67 
=> build(gradle): fix portalInit task graph

build.gradle
Every task run will generate a *build/reports/visteg.dot* file.
This file can be converted to svg or png using graphviz `dot -Tsvg visteg.dot -O -v`.
Ref: https://github.com/mmalohlava/gradle-visteg
Example output:
=> build(gradle): add plugin that generates a visualization of task graph

.travis.yml
Ensures that uPortal also functions with latest OpenJDK version.
=> ci(travis): add open jdk 8 to test matrix

data/quickstart/fragment-layout/all-lo.fragment-layout.xml, data/quickstart/portlet-definition/feedback-navigation.portlet-definition.xml
-   [] [message properties][] have been updated with new phrases
Adding new feature to uPortal. It is a portlet, with a helpful reminder to submit feedback and a link to feedback, which is in the layout, specifically all-lo. It is just under the tips portlet.
https://issues.jasig.org/browse/UP-4960
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/prop …
=> UP-4960: Add feedback navigation portlet to layout

etc/tomcat/bin/setenv.bat
This issue seems to me like something that should be caught in the CI.  I would like it very much if we can enhance the Gradle setup and/or the CI setup so that this kind of thing can be caught.
=> Add missing '+' character within '-XX:+UseG1GC' inside setenv.bat

build.gradle, gradle/tasks/hsql.gradle, gradle/tasks/portal.gradle, gradle/tasks/tomcat.gradle
=> feat: wait for server ports to come online, announce when tomcat is ready

gradle.properties
Upgrade WeatherPortlet to 1.1.6 to resolve the broken city links for Yahoo.  Reference to https://issues.jasig.org/browse/WPT-87
=> WPT-87:  Upgraded WeatherPortlet to 1.1.6

gradle/tasks/tomcat.gradle
This gives a quick way to start Tomcat with JPDA remote debugging enabled on port 8000.
=> feat(build): add gradle tomcat start with jpda property

build.gradle
Make it easier to setup uPortal-start with Eclipse and Intellij
=> build(gradle): allow generation of project files to intellij and eclipse

build.gradle
This patch adds support for custom Gradle tasks (such as #156) that are not (yet) a part of uPortal-start. 
I'm trying to keep our modifications to our fork uPortal-start limited as much as possible and I think this will add some flexibility without having to worry about resolving merge conflicts in the future. …
=> Added support for custom Gradle tasks

.travis.yml, .travis/conf/database/mariadb/announcements.properties, .travis/conf/database/mariadb/calendar.properties, .travis/conf/database/mariadb/global.properties, .travis/conf/database/mariadb/mariadb-server.cnf, .travis/conf/database/mariadb/news-reader.properties, .travis/conf/database/mariadb/simple-cms.properties, .travis/conf/database/mariadb/uPortal.properties, docs/database/README.md, docs/database/mariadb.md, docs/database/mysql.md, docs/fr/database/README.md, docs/fr/database/mariadb.md, docs/fr/database/mysql.md, overlays/Announcements/build.gradle, overlays/BookmarksPortlet/build.gradle, overlays/CalendarPortlet/build.gradle, overlays/NewsReaderPortlet/build.gradle, overlays/SimpleContentPortlet/build.gradle, overlays/build.gradle
Adding dependency management for dataInit of all applications (uPortal and all portlets) on MariaDB (can work for MySQL) with the documentation and travis test on MariaDB.
This commit depends on https://github.com/Jasig/uPortal/pull/1176, which define two specifics dependencies that must be deployed on OSS Sonatype before.
[commit guidelines]: …
=> For MariaDB conf deployment + doc + test

etc/portal/uPortal.properties
Depends on https://github.com/Jasig/uPortal/pull/1318
Remove useless property as the RemoteUserPersonManager is enabled by default
[WCAG …
=> Cleaning about PersonManager property

data/quickstart/portlet-definition/waffle-menu.portlet-definition.xml
Self closing custom tags are not part of the spec.
=> fix: custom elements must have a closing tag

data/quickstart/portlet-definition/favorites-carousel.portlet-definition.xml
Non minified version of vue can cause IE to randomly hang while loading the page.
=> fix: use production minified vue and component

gradle/tasks/properties.gradle, gradle/tasks/tomcat.gradle
Provide a way to set the PORTAL_HOME env variable from uPortal-start task tomcatStart, also it permit to override the default value by passing -Dportal.home=path dynamically from command line.
It avoids to set PORTAL_HOME environment variable whereas we can pass it from command line in some case. With this change this permit to apply the portal.home value in all task.
An other improvement would be to add into java env all -D args passed from command line. (but seems complicated with gradle) …
=> Possibility to set PORTAL_HOME in tomcatStart task from cmd

renovate.json
renovate was failing from exception:
```
Gradle command gradle --init-script init.gradle dependencyUpdates -Drevision=release failed. Exit code: 1. (repository=Jasig/uPortal-start)
"err": {
"name": "ChildProcessError",
"code": 1,
"childProcess": {},
"stdout": "Parallel execution is an incubating feature.\n> Task :buildSrc:compileJava NO-SOURCE\n> Task :buildSrc:compileGroovy NO-SOURCE\n> Task :buildSrc:processResources NO-SOURCE\n> Task :buildSrc:classes UP-TO-DATE\n> Task :buildSrc:jar\n> Task :buildSrc:assemble\n> Task :buildSrc:compileTestJava NO-SOURCE\n> Task :buildSrc:compileTestGroovy NO-SOURCE\n> Task :buildSrc:processTestResources NO-SOURCE\n> Task …
```
=> fix: renovate bot, includes build src folder so that custom plugin will resolve

data/quickstart/portlet-definition/admin-dashboard.portlet-definition.xml, data/quickstart/portlet-definition/favorites-carousel.portlet-definition.xml, data/quickstart/portlet-definition/notification-icon.portlet-definition.xml, data/quickstart/portlet-definition/waffle-menu.portlet-definition.xml
first paint/render is currently blocked by web component loading, this
defers loading of components so page can render, then fill in web
components a moment later in a second page paint.
This improves perceived load time of uPortal.
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smi …
=> refactor: defer loading of web components, unblocking first render

etc/tomcat/conf/server.xml
Having compression for JavaScript, JSON, and HTML significantly improves load times in worsened network conditions.
This can be disabled if a server fronting uPortal also is also compressing content.
=> feat: enable compression in Tomcat by default

data/quickstart/fragment-layout/academics-lo.fragment-layout.xml, data/quickstart/fragment-layout/staff-lo.fragment-layout.xml, data/quickstart/portlet-definition/notification-banner.portlet-definition.xml, data/quickstart/portlet-definition/notification-icon.portlet-definition.xml, data/quickstart/portlet-definition/notification-list.portlet-definition.xml, data/quickstart/portlet-definition/notification-modal.portlet-definition.xml, gradle.properties, overlays/resource-server/build.gradle
This pull request updates uPortal-start to Notification widgets released from [notification-web-components](https://github.com/uPortal-contrib/notification-web-components), rather than included as a part of the NotificationPortlet project.
[WCAG 2.0 AA]: …
=> chore(dependencies): update notificationPortletVersion to 4.5.3 and notificationWebComponentsVersion to 1.0.2

docker/Dockerfile
Leverages the health check endpoint added in https://github.com/Jasig/uPortal/pull/1333
/cc @laurenra7
=> refactor: use health-check endpoint for Docker HEALTHCHECK

docs/en/data/index.md, docs/en/data/lockdown-layouts.md
-   [X] documentation is changed or added
Describe how to lock down non-admin user layouts.
=> docs(data): How to lock down non-admin layouts

etc/tomcat/conf/server.xml
For issue https://github.com/Jasig/uPortal-start/issues/365
Set startStopThreads=0 for improved tomcat startup performance on a larger variety of systems.
=> GH-365. Use stopStartThreads=0

etc/portal/uPortal.properties, gradle.properties
Defaulting CAS `encodeServiceUrl` to false for embedded CAS server. This is a follow-up to #372 
=> fix: defaulted CAS encodeServiceUrl to false for embedded CAS server

overlays/NotificationPortlet/src/main/resources/logback.xml
Corrected logger configuration for the NotificationPortlet overlay from `org.jasig.portlet.notification` to `org.jasig.portlet.notice`. The package name is correct in jasig/NotificationPortlet, but is incorrect in uPortal-start.
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2C …
=> fix(NotificationPortlet): corrected logger configuration

overlays/NewsReaderPortlet/build.gradle
./gradlew :overlays:NewsReaderPortlet:dataImport -Ddir=...
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies …
=> fix: restore newsreader import feature

overlays/uPortal/build.gradle
Started receiving errors about line 145 in overlays/uPortal/build.gradle around Xerces version conflicts. `FileNameFinder` is deprecated. Replacing this with FileTree resolved the error.
=> fix: correct Xerces classpath loading conflict

renovate.json
the current gradle manager appears to be getting hung up due to some of the additional plugins applied.
Since `gradle-lite` doesn't run plugins, it may be able to bypass the issues seen.
https://github.com/renovatebot/renovate/blob/c43a4dc328bedf55777a641bc8477ff5a49a1722/lib/manager/gradle-lite/readme.md
[commit guidelines]: …
=> chore: switch renovate to use gradle lite updater

.travis.yml, gradle/tasks/tomcat.gradle
This pull request simply adds a `tomcatRestart` Gradle task that first runs `tomcatStop` then `tomcatStart`. This can be very handy when debugging a uPortal setup and shouldn't be a maintenance burden.
Have a nice day.
[WCAG 2.0 AA]: …
=> Add a `tomcatRestart` Gradle task

docs/en/tomcat/debugging-with-jpda.md
the parametter passed as `-- with-jpda` return an error 
```
Problem configuring task :tomcatStart from command line.
> Unknown command-line option '--with-jpda'.
```
And so to fix the problem and to read the param as a project's property we need to pass it with -P argument
[commit guidelines]: …
=> Doc: fix command from gradle change

docker/Dockerfile
This addresses an issue where the resulting image is failing the healthcheck since it does not have `wget`.
```
$ sudo docker container ls --filter name="my-dev_uPortal_1"
CONTAINER ID   IMAGE                   COMMAND                  CREATED         STATUS                     PORTS      NAMES
aef9786ceac9   apereo/uportal:latest   "/tomcat/bin/catalin…"   4 minutes ago   Up 4 minutes (unhealthy)   8080/tcp   my-dev_uPortal_1
```
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/.github/CONTRIBUTING.md#c …
=> fix: updated Dockerfile to add wget to image to support the healthcheck

data/quickstart/portlet-definition/notification-icon.portlet-definition.xml
Setting the MIME type si required to avoid X-Content-Type-Options: nosniff browser blocking
[WCAG 2.0 AA]: …
=> fix: set type to avoid nosniff browser blocking

etc/portal/uPortal.properties
Document new option for selecting Ehcache configuration file. uPortal will have two of these configuration files, one with and one without JGroups support.
=> config:add property for Ehcache config file

gradle/tasks/tomcat.gradle
Extracting the code that configures Tomcat so that implementers can target existing Tomcat installs. This happens enough in current higher ed environments where Ops prefers to use their own Tomcat installations.
=> feat: separate out tomcatConfig task from tomcatInstall

data/quickstart/fragment-layout/welcome-lo.fragment-layout.xml, data/quickstart/portlet-definition/bookmarks.portlet-definition.xml
=> fix: renamed pbookmarks portlet definition to bookmarks

etc/tomcat/bin/setenv.bat, etc/tomcat/bin/setenv.sh
While uPortal and portlets are not susceptible to CVE-2021-44228, including the startup parameters to help guard custom code that may include Log4j2.
=> chore: set startup parameters to secure Log4j2

overlays/ResourceServingWebapp/build.gradle
ResourceServingWebapp needed to include two JAXB libraries in order to run with a Java 11 JDK.
Because we use a very old/outdated version of ResourceServingWebapp, it was easier to add the dependencies to the overlay rather than trying to update the actual project.
[WCAG 2.0 AA]: …
=> UPSE-293: update for ResourceServingWebapp to run w/ Java 11

overlays/cas/build.gradle
The CAS webapp was failing to startup when running Tomcat with Java 11.
Issue is that it needs newer versions of AspectJ jars.
Updated overlay build.gradle to replace older jars with newer ones that work with Java 11.
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash …
=> UPSE-362: updates for CAS Webapp to run w/ Java 11

gradle/tasks/properties.gradle, overlays/uPortal/build.gradle
-   [ ] the [individual contributor license agreement][] is signed
-   [ ] commit message follows [commit guidelines][]
Add a new task, skinDeployFiles, so that skin development does not require Tomcat restarts and `tomcatDeploy`.
=> feat: add task skinDeployFiles

buildSrc/src/main/groovy/scaldingspoon/gradle/WarOverlayPlugin.groovy, overlays/build.gradle
War Overlay Plugin is no longer available from JCenter, and it will not build from it's repo. 
Copying the plugin directly into this project.
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/ …
=> fix: copy in War Overlay Plugin
