.gitignore, README.md, build.gradle, etc/hsql/hsqldb.sqltool.rc, etc/tomcat/bin/setenv.bat, etc/tomcat/bin/setenv.sh, gradle/tasks/hsql.gradle, gradle/tasks/portal.gradle, gradle/tasks/properties.gradle, gradle/tasks/tomcat.gradle
https://issues.jasig.org/browse/UP-4868
Windows fixes for existing Gradle tasks
=> UP-4868:  Fix Gradle-based CLI tools within uPortal-start on Windows

.travis.yml, README.md, appveyor.yml, overlays/cas/build.gradle
Resolves #16
Includes #15
Adds Travis CI as linux ci.
Adds AppVeyor as windows ci.
=> Issue #16: Setup continuous integration

.travis.yml
Adds OS X 10.12 to the Travis CI build matrix.
=> Setup continuous integration for MacOS

.travis.yml, appveyor.yml, gradle/tasks/tomcat.gradle
Resolves unaddressed comment in #7
Use Gradle Delete task for clearing tomcat logs
=> UP-4868: Resolve pull request comments

README.md, gradle/tasks/tomcat.gradle
Added section 'First Time Running uPortal via uPortal-start'
-   [x ] commit message follows [commit guidelines][]
-   [x ] documentation is changed or added
First time installing/running uPortal5 / uPortal-start and gathered some learning points into this 'first time users' section.
=> Added notes for first-time users

SUPPORT.md
Direct people towards asking questions on the uPortal mailing list.
Adapted from the Angular support file.
See https://github.com/blog/2400-support-file-support for github support.
=> docs: Add support file guiding questions to the uPortal user list

data/base/portlet-definition/dynamic-respondr-skin.portlet-definition.xml
Use apps/preferences-desktop-theme.png instead of actions/preferences-desktop-theme.png
@see https://github.com/Jasig/resource-server/blob/master/resource-server-content/src/main/webapp/rs/tango/0.8.90/32x32/apps/preferences-desktop-theme.png
=> NOJIRA: Fix HTTP 404 on dynamic-respondr-skin.portlet-definition.xml

docs/database/db2.md, docs/database/index.md, docs/index.md, docs/tomcat/fronting-with-httpd.md, docs/tomcat/index.md, docs/tomcat/ssl-configuration.md
Follow up to <https://github.com/Jasig/uPortal/pull/981>.
Based off work in <https://github.com/Jasig/uPortal/pull/894>.
Thanks to @aperto and @vertein for handling the port from confluence to markdown.
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2C …
=> docs(database, tomcat): Port over database and tomcat documentation from uPortal

etc/portal/global.properties, etc/portal/uPortal.properties, gradle.properties, gradle/tasks/tomcat.gradle, overlays/uPortal/src/main/resources/properties/contextOverrides/overridesContext.xml
https://issues.jasig.org/browse/UP-4918
[UP-4918](https://issues.jasig.org/browse/UP-4918) has been merged into `uPortal`.  This PR includes some minor tweaks to help you take advantage of those updates from within `uPortal-start`.
[WCAG 2.0 AA]: …
=> UP-4918:  Some support for leveraging these changes (UP-4918) in uPortal-start

gradle.properties, overlays/uPortal/build.gradle, overlays/uPortal/package-lock.json, overlays/uPortal/package.json
Define a prepareSkinResources task that provides support for custom skins in uPortal-start
This PR is a uPortal-start corollary to https://github.com/Jasig/uPortal/pull/987. 
=> UP-4924:  Gradle uPortal skin/theme tasks

gradle.properties
New release of Announcements that supports `global.properties` and `announcements.properties`
=> Update Announcements to 2.3.1

buildSrc/src/main/groovy/org/apereo/portal/start/gradle/plugins/GradleImportExportPlugin.groovy, buildSrc/src/main/groovy/org/apereo/portal/start/gradle/plugins/GradleTomcatDeployPlugin.groovy, buildSrc/src/main/resources/buildDefaults.properties, gradle/tasks/hsql.gradle, gradle/tasks/portal.gradle, gradle/tasks/properties.gradle, gradle/tasks/tomcat.gradle
-   [x ] the [individual contributor license agreement][] is signed
Allows the use of OS ENV vars and full path file locations outside of
project directory.
=> Can now customize tomcat location

gradle.properties
This update is required for the `skinGenerate` task.
=> Bump uPortalVersion to 5.0.0-M8

gradle.properties
=> Bump uPortalVersion to 5.0.0-M10 and +resourceServerVersion to 1.0.48

gradle.properties
This PR updates uPortal-start to the official 5.0.0 uPortal release.
=> Update uPortal-start to uPortalVersion=5.0.0

gradle.properties
Corrected minor typo in gradle.properties
=> Corrected minor typo in gradle.properties

docs/database/oracle.md
Migrated (from https://wiki.jasig.org/display/UPM43/Oracle) and updated documentation for configuring uPortal with Oracle
=> Added documentation for configuring uPortal with Oracle

etc/tomcat/bin/setenv.bat, etc/tomcat/bin/setenv.sh
-   [x ] the [individual contributor license agreement][] is signed
Defaults the garbage collector to G1GC if no other garbage collector has been defined in CATALINA_OPTS
=> Sets G1GC to default if no garbage collector defined

data/quickstart/portlet-definition/uportal-links.portlet-definition.xml
Updated link to documentation in the uPortal Links portlet
=> Updated link to documentation in the uPortal Links portlet

gradle.properties
=> Update uPortalVersion to 5.0.1

gradle.properties, overlays/uPortal-home/build.gradle
=> feat: add variable placeholder for uPortal home version

data/base/portlet-definition/dynamic-respondr-skin.portlet-definition.xml
Removed css extension from PREFdynamicSkinName
=> Removed css extension from PREFdynamicSkinName

gradle.properties
Released today!
https://github.com/Jasig/uPortal/releases/tag/v5.0.2
=> Update to uPortalVersion 5.0.2

gradle.properties
Includes cross platform fixes, particularly improving the experience on Windows.
https://github.com/Jasig/AnnouncementsPortlet/releases/tag/Announcements-2.3.2
/cc @cbeach47 
=> chore(gradle): upgrade announcements portlet to version 2.3.2

data/base/permission_owner/UP_PORTLET_SUBSCRIBE.permission-owner.xml, gradle.properties
[uPortal 5.0.3 Release Notes](https://github.com/Jasig/uPortal/releases/tag/v5.0.3)
=> chore: upgradle uPortal version to 5.0.3

gradle.properties
This PR updates the `uPortalVersion` property to 5.0.4, which was published today.
=> chore:  update uPortalVersion to 5.0.4

gradle.properties
-   [ ] the [individual contributor license agreement][] is signed
-   [ ] commit message follows [commit guidelines][]
Release notes:  https://github.com/Jasig/uPortal/releases/tag/v5.0.5
=> Update uPortalVersion to 5.0.5

data/base/portlet-definition/reset-my-layout.portlet-definition.xml
=> chore(doc): correct grammar in description of reset-my-layout.portlet-definition.xml

gradle.properties
=> chore(deps): upgrade Announcements Portlet to version 2.3.3

overlays/Announcements/build.gradle, overlays/BookmarksPortlet/build.gradle, overlays/CalendarPortlet/build.gradle, overlays/FeedbackPortlet/build.gradle, overlays/NewsReaderPortlet/build.gradle, overlays/NotificationPortlet/build.gradle, overlays/SimpleContentPortlet/build.gradle, overlays/jasig-widget-portlets/build.gradle, overlays/uPortal/build.gradle
Excluding hsqldb-*.jar that comes from the prebuilt artifacts. This addresses #119
=> Issue #119:  Excluding hsqldb-*.jar that comes from the prebuilt artifacts

gradle.properties
New release of Weather;  corrects some mixed content issues.
=> chore(deps)/update Weather portlet to 1.1.7

gradle.properties
brings in accessibility fixes, allowing for uPortal high contrast colors to be applied to the portlet.
=> chore(deps): update announcments and calendar portlets

gradle.properties
https://github.com/Jasig/AnnouncementsPortlet/releases/tag/Announcements-2.3.6
=> chore(deps): update announcements portlet to version 2.3.6

gradle.properties
https://github.com/Jasig/uPortal/releases/tag/v5.1.0-M2
https://github.com/Jasig/uPortal/releases/tag/v5.1.0-M3
https://github.com/Jasig/uPortal/releases/tag/v5.1.0-M4
=> chore(deps): update uPortal version to 5.1.0 milestone 4

data/base/portlet-definition/search.portlet-definition.xml
https://issues.jasig.org/browse/UP-4977
=> Added RESTSearch portlet preference to the Search portlet definition

gradle.properties
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.10.0
=> chore(deps): update node to version 8.10.0

docs/index.md, docs/integrations/index.md, etc/portal/uPortal.properties
=> doc(cors): Add comment on format for cors.allowed.origins

gradle/tasks/tomcat.gradle
=> fix: correct tomcatZip and tomcatTar.

docs/database/index.md
=> doc: Update database doc to match uPortal 5.

build.gradle, gradle/tasks/properties.gradle
From issue #135 - Java version check implemented for all projects.  Currently Java 8 is required.
=> #135 Implement Java version check.

gradle.properties
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.11.1
=> chore(deps): update node js to version 8.11.1

gradle.properties
https://github.com/Jasig/uPortal/releases/tag/v5.1.0-M6
=> chore(deps): update uPortal version to 5.1.0 milestone 6

gradle/wrapper/gradle-wrapper.properties
=> chore: update gradle to version 4.7

docker/Dockerfile-cli
=> chore: update gradle image version

gradle.properties
https://github.com/Jasig/uPortal/releases/tag/v5.1.0
=> chore(deps): update uPortal version to 5.1.0 stable

gradle.properties, overlays/uPortal/package-lock.json
=> chore: update node.js to version 10 and npm to version 5

gradle.properties
=> chore(deps): update common codecs to version 1.11

gradle.properties
Release notes:  https://github.com/Jasig/uPortal/releases/tag/v5.1.1
=> chore(deps): update uPortalVersion to 5.1.1

gradle.properties, overlays/uPortal/package-lock.json
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.1.0
=> chore: update Node.js to version 10.1.0

overlays/uPortal/package-lock.json, overlays/uPortal/package.json
https://github.com/less/less.js/blob/master/CHANGELOG.md#300
=> chore(deps): upgrade less js to version 3.0.4

etc/tomcat/conf/context.xml
=> Update context.xml to remove session persistence warning

docs/README.md, docs/data/index.md, docs/data/timeout.md
=> docs(timeout): Add documentation on setting session timeout by group.

docs/database/postgresql.md
Add instructions for setting up uPortal 5 to connect to an existing PostgreSQL database.
Credit to @jonathanmtran for the existing Oracle documentation this was modeled after.
=> NOJIRA: Add documentation for using uPortal 5 with a PostgreSQL database

gradle.properties
=> Update uPortalVersion to 5.1.2

data/quickstart/portlet-definition/esup-filemanager-demo.portlet-definition.xml
Issue #175 
We still need to understand...
- Why the right-click menu isn't working
- Why the file-manager CSS is impacting the Calendar portlet
=> Issue #175:  ESUP file-manager troubleshooting

etc/skin/skinName/less/variables.less
Comments for `@color4*` and `@color5*` mentions `color3`.
=> Updated comments in variables.less

gradle.properties
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.6.0
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.5.0
=> chore: update node to version 10.6.0

docs/data/timeout.md
=> Add <owner> to example in timeout.md

gradle.properties
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.7.0
=> chore: update node to version 10.7.0

overlays/uPortal/package-lock.json, overlays/uPortal/package.json
https://github.com/less/less.js/blob/master/CHANGELOG.md#371
=> chore: update less 3.7.1

etc/tomcat/bin/setenv.bat, etc/tomcat/bin/setenv.sh
Check for previously set allocation of heap space
=> Heap space

gradle.properties
https://github.com/Jasig/uPortal/releases/tag/v5.2.0
=> chore: update uPortal to version 5.2.0

etc/portal/uPortal.properties
This is a port of Jasig/uPortal#1264. This is dependent on #190 
=> Updated etc/portal/uPortal.properties regarding OpenID custom claims

etc/portal/uPortal.properties
=> docs: add placeholder to make it easier to enable swagger docs

docs/tomcat/debugging-with-jpda.md
=> docs: correct jpda sample terminal command

gradle.properties
=> chore: update uPortal to version 5.2.1

gradle.properties
=> chore:  update uPortalVersion to 5.2.2

README.md
Added documentation in README.md for modifying text strings defined in the uPortal project without having to modify the uPortal project. …
=> Text strings documentation

docs/fr/frontend/README.md, docs/fr/frontend/RENDERING_PIPELINE.md, docs/fr/frontend/SKIN_UPORTAL.md, docs/fr/frontend/USING_ANGULAR_fr.md, docs/frontend/README.md, docs/frontend/RENDERING_PIPELINE.md, docs/frontend/SKINNING_UPORTAL.md, docs/frontend/USING_ANGULAR.md, etc/skin/skinList.xml, etc/skin/skinName/skin.xml, overlays/uPortal/build.gradle
=> enh(#199): Enhance skinGenerate and add documentation. 

gradle.properties
https://github.com/uPortal-contrib/uPortal-web-components/blob/master/CHANGELOG.md#174---2018-08-17
=> chore: update web components to version 1.7.4

gradle.properties
This update includes a recent fix for attachments in Announcements-generated RSS.
=> chore:  update announcementsPortletVersionto 2.4.2

gradle.properties
https://github.com/Jasig/uPortal/releases/tag/v5.2.3
=> chore: update uPortal to version 5.2.3

gradle.properties
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.11.0
=> chore: update node.js to version 10.11.0

docker/Dockerfile-cli
=> chore: update docker gradle to version 4.10

overlays/uPortal/build.gradle
=> fix: Added a check to skip prepareSkinResources for dataImport tasks

etc/tomcat/bin/setenv.sh
Resolves #229 
Spaces added before ] at the end of 2 conditional expressions to resolve an error on tomcat startup.
=> fix(#229) Resolve tomcat startup error

gradle.properties
https://github.com/Jasig/uPortal/releases/tag/v5.3.1
=> chore: update uPortal to version 5.3.1

data/quickstart/portlet-definition/favorites-carousel.portlet-definition.xml, data/quickstart/portlet-definition/waffle-menu.portlet-definition.xml, gradle.properties, overlays/resource-server/build.gradle
Includes vue in internal cdn, allows vue version to be managed by package manager, updates components with latest fixes.
=> refactor: include vue as a webjar, update uPortal web components

etc/portal/uPortal.properties
=> fix: remove temporary patch, uPortal 5.3.1 is now bundled

gradle.properties
=> chore: update uPortal to version 5.3.2

gradle.properties
Includes new features to grid component, and browser compatibility fixes
=> chore: update uportal web components to version 1.16.0

gradle.properties
=> chore: update uPortal web components to version 1.16.1

gradle.properties
Includes an additional icon fix for the content carousel.
=> chore: update uPortal web components to version 1.16.2

gradle.properties
This version includes the ability to define custom sort orders in the esco content menu.
=> chore: update uPortal web components to version 1.17.0

gradle.properties
=> chore: update uportal web components to version 1.18.1

gradle.properties
https://nodejs.org/en/blog/vulnerability/november-2018-security-releases
=> chore: upgrade node js to version 10.14.0

gradle.properties
https://github.com/uPortal-contrib/uPortal-web-components/blob/master/CHANGELOG.md#1190---2018-12-06
=> chore: update uPortal web components to version 1.19.0

gradle.properties
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.14.2
https://github.com/vuejs/vue/releases/tag/v2.5.21
https://github.com/vuejs/vue/releases/tag/v2.5.20
https://github.com/vuejs/vue/releases/tag/v2.5.19
https://github.com/vuejs/vue/releases/tag/v2.5.18
https://github.com/vuejs/vue/releases/tag/v2.5.18-beta.0
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/r …
=> chore: update vue js and node js to latest stable versions

gradle.properties
=> chore:  update uPortalVersion to 5.4.0

gradle.properties
This update the uPortal version, and uportal-contrib web-components version to the latest
[WCAG 2.0 AA]: …
=> chore(deps): update uPortalVerison + web-components

gradle.properties
=> chore: update uPortal web components

gradle.properties
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.15.1
=> chore: node 10.15.1

gradle.properties
```
-announcementsPortletVersion=2.4.2
+announcementsPortletVersion=2.4.4
-bookmarksPortletVersion=1.1.1
-calendarPortletVersion=2.6.0
+bookmarksPortletVersion=1.2.1
+calendarPortletVersion=2.6.1
-casProxyTestPortletVersion=1.0.1
+casProxyTestPortletVersion=1.0.2
-jasigWidgetPortletVersion=2.2.7
+jasigWidgetPortletVersion=2.3.0
-webProxyPortletVersion=2.3.1
+webProxyPortletVersion=2.3.2
```
[message properties]: …
=> chore: update 5 portlets to lastest patch versions

data/base/portlet-definition/attachments.portlet-definition.xml, data/quickstart/portlet-definition/background-preference.portlet-definition.xml, data/quickstart/portlet-definition/emergency-alert.portlet-definition.xml, data/quickstart/portlet-definition/tips.portlet-definition.xml, data/quickstart/portlet-definition/weather.portlet-definition.xml, gradle.properties
-   [ ] the [individual contributor license agreement][] is signed
-   [ ] commit message follows [commit guidelines][]
=> chore: update uPortalVersion to 5.5.0

renovate.json
Reduce update PR noise by grouping all artifacts in uPortal and uPortal web components together into single PRs.
=> chore: group uportal updates and uportal web component updates

gradle.properties, overlays/uPortal/build.gradle
=> chore: update gradle node plugin and embedded node js version

gradle.properties
=> chore: update vue js to version 2.6.10

docs/en/sysadmin/docker.md
=> doc(docker): Initial write-up on Docker usage

gradle.properties
=> chore:  Upgrade Bookmarks (1.2.2) and Announcements (2.4.5)

docs/en/sysadmin/tomcat-env-vars.md
=> docs(tomcat): Add doc on how to externalize Tomcat config

etc/portal/uPortal.properties
=> chore(prop): Add signatureAlgorithm to uPortal.properties

docs/en/content/resource-server.md, docs/en/content/webjars.md
=> doc(rs): Describe adding and using static files

docs/en/database/oracle.md
=> doc: Update Oracle DB doc with easier approach

docs/en/database/oracle.md
=> doc(oracle): Update Oracle db doc to use Maven Central

docs/en/integrations/README.md
Docs on how to create a custom module for uPortal-start
=> doc:initial write-up on custom modules

README.md
Note that JDK 8 is required, link to Corretto JDK 8 which is [still actively maintained (and will be until June 2023)](https://aws.amazon.com/corretto/faqs/).
related to https://github.com/Jasig/uPortal/issues/1955
[WCAG 2.0 AA]: …
=> docs: note JDK 8 is required

renovate.json
the dashboard/master issue shows what PRs are open/pending/closed,
and gives utilities to manage the issues from one place.
=> chore: configure renovate to create a dashboard issue

.travis.yml, gradle.properties, overlays/uPortal/build.gradle
moowork gradle node plugin is no longer maintained
=> chore: switch to gradle node

etc/tomcat/conf/server.xml
-   [ ] commit message follows [commit guidelines][]
=> fix: disable AJP port

overlays/uPortal/package-lock.json
=> chore: update package lock file

overlays/build.gradle
For testing https://github.com/Jasig/uPortal/pull/2157
Part of fix for: https://github.com/Jasig/uPortal-start/issues/468
[WCAG 2.0 AA]: …
=> test: add jitpack datasource

gradle.properties
Updated uPortal to the latest (5.9.0).
Updated a variety of the supporting portlets to their latest versions.
=> chore: update portlets and uPortal

etc/tomcat/bin/setenv.sh
=> chore: prefer IPv4 over IPv6

overlays/uPortal/build.gradle
=> fix: need to only grab the top skin .less file

README.md, data/quickstart/portlet-definition/uportal-links.portlet-definition.xml, docs/en/README.md, docs/fr/README.md
updated jasig.github.io URLs to uPortal-Project.github.io
=> docs: updated jasig.github.io URLs to uPortal-Project.github.io

data/quickstart/fragment-layout/academics-lo.fragment-layout.xml, gradle.properties
=> chore: update from uPortal 5.9.0 to 5.10.0

docker/Dockerfile, docker/Dockerfile-cli
-   [x] [message properties][] have been updated with new phrases
Update base docker images to supported JDK and Gradle versions.
[WCAG 2.0 AA]: …
=> build: update base docker images

gradle.properties
=> chore: update from uPortal 5.10.0 to 5.11.0

gradle.properties
=> chore: upgrade uPortal-web-components from 1.36.0 to 1.37.0

gradle.properties, gradle/tasks/perf.gradle, overlays/cas/build.gradle
It was unclear where version numbers were used which led to changes that broken the build/portal. Comments and re-organization hopefully clarifies this.
=> chore: comment and organize gradle.properties

overlays/uPortal/src/main/resources/properties/contextOverrides/overridesContext.xml
Updated overridesContext.xml to remove the schema xsd version to follow Spring best practices
=> Remove spring version from xml schemaLocation

docs/en/database/mariadb.md, docs/fr/database/mariadb.md
Update the documentation about the dialect to use with Mysql and MariaDB to one provided by hibernate.
[WCAG 2.0 AA]: …
=> doc: update MariaDB doc

gradle.properties
Upgrading uPortal to 5.12.0 - https://github.com/uPortal-Project/uPortal/releases/tag/v5.12.0
=> chore - upgrade uPortal to 5.12.0

gradle.properties
=> chore: upgrade WebProxyPortlet from 2.3.4 to 2.3.7

etc/tomcat/bin/windows-env.txt
Capture details for configuring Tomcat when using the Windows Service configuration tool.
=> chore: add instructions for Tomcat as a Windows Service

gradle.properties
=> chore: upgrade to NewsReaderPortlet v5.0.5

gradle.properties, overlays/resource-server/build.gradle
=> chore: upgrade uPortal and portlets to Java11-compatible versions

package-lock.json, tests/api/analytics.spec.ts, tsconfig.json
-   [x] [message properties][] have been updated with new phrases
=> bugfix: playwright fixes

gradle.properties
=> chore: upgrade uportal to v5.16.1

build.gradle, gradle.properties, overlays/uPortal/package-lock.json, overlays/uPortal/package.json, package-lock.json
-   [x] [message properties][] have been updated with new phrases
resolves uPortal-Project/uPortal-start#650
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cfl …
=> chore: update node js, less, and gradle node version

.github/workflows/CI.yml
=> chore(ci): setup GitHub action for gradle
